resources:
  - name: app_source
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/basic-api
      branches:
        include: {{gitBranch}}

  - name: app_docker
    type: Image
    configuration:
      registry: art_master
      sourceRepository: docker-local
      imageName: pipe-master.jfrog.info:8082/docker-local/basicapi
      imageTag: latest

  - name: app_test_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0

pipelines:
  - name: jenkins_demo_1
    configuration:
      nodePool: static-node-pool
    steps:
      - name: build_app
        type: DockerBuild
        configuration:
          affinityGroup: buildAndPush
          inputResources:
            - name: app_source
          dockerFileLocation: "."
          dockerFileName: Dockerfile
          dockerImageName: "pipe-master.jfrog.info:8082/docker-local/basicapi"
          dockerImageTag: "${res_app_source_branchName}.${run_number}"
        execution:
          onStart:
            - pushd $res_app_source_resourcePath
            - export OPTIONS=""
            - if [ "$res_app_source_branchName" == "master" ]; then OPTIONS="--production"; fi
            - npm install $OPTIONS
            - if [ $res_app_source_branchName == "dev" ]; then npm test; fi
            - popd

      - name: push_app
        type: DockerPush
        configuration:
          affinityGroup: buildAndPush
          targetRepository: docker-local
          integrations:
            - name: art_master
          inputSteps:
            - name: build_app
          outputResources:
            - name: app_docker

      - name: test_app
        type: Jenkins
        configuration:
          jenkinsJobName: basic-api-mb
          jenkinsBranchName: {{gitBranch}}
          inputResources:
            - name: app_docker
          buildParameters:
            runNumber: ${run_number}
            imageName: ${res_app_docker_imageName}
            imageTag: ${res_app_docker_imageTag}
          integrations:
            - name: jenkins
          outputResources:
            - name: app_test_results

      - name: lastStep
        type: Bash
        configuration:
          integrations:
            - name: jenkins
          inputResources:
            - name: app_test_results
        execution:
          onExecute:
            - printenv | grep res_app_test_results
            - printenv | grep int_jenkins_
