resources:
  - name: app_source_mb
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/basic-api
      branches:
        include: ^{{gitBranch}}$

  - name: app_docker
    type: Image
    configuration:
      registry: art_master
      sourceRepository: docker-local
      imageName: basicapi
      imageTag: latest

  - name: app_test_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0

pipelines:
  - name: jenkins_demo_mb
    steps:
      - name: build_app
        type: DockerBuild
        configuration:
          affinityGroup: buildAndPush
          inputResources:
            - name: app_source_mb
          dockerFileLocation: "."
          dockerFileName: Dockerfile
          dockerImageName: "http://pipe-master.jfrog.info:8082/docker-local/basicapi"
          dockerImageTag: "{{gitBranch}}.${run_number}"
        execution:
          onStart:
            - pushd $res_app_source_mb_resourcePath
            - export OPTIONS=""
            - if [ {{gitBranch}} == "master" ]; then OPTIONS="--production"; fi
            - npm install $OPTIONS
            - if [ {{gitBranch}} == "dev" ]; then npm test; fi
            - popd

      - name: push_app
        type: DockerPush
        configuration:
          affinityGroup: buildAndPush
          targetRepository: docker-local
          integrations:
            - name: art_master
          inputSteps:
            - name: build_app
          outputResources:
            - name: app_docker

      - name: test_app
        type: Jenkins
        configuration:
          jenkinsJobName: app_test
          jenkinsBranchName: {{gitBranch}}
          inputResources:
            - name: app_docker
          buildParameters:
            foo: bar
          integrations:
            - name: jenkins
          outputResources:
            - name: app_test_results

      - name: lastStep
        type: Bash
        configuration:
          inputResources:
            - name: app_test_results
        execution:
          onExecute:
            - printenv | grep app_test_results
